FROM kbs_backend:latest

ARG APP_DIR=/home/app

# RUN apt-get install -yq nginx # RMEOOOOOOOO
# COPY nginx.conf $APP_DIR/tmp/
# RUN cp $APP_DIR/tmp/nginx.conf /etc/nginx/sites-available/api
# RUN rm /etc/nginx/sites-enabled/default
# RUN ln -s /etc/nginx/sites-available/api /etc/nginx/sites-enabled/default

COPY kbs_backend $APP_DIR

WORKDIR $APP_DIR

# Setup the server
EXPOSE 8000
EXPOSE 80

# Clean-up
RUN rm -rf /kbs_backend/

#CMD ["nginx", "-g", "daemon off;"]
CMD ["uwsgi", "--ini", "/home/app/kbs_backend/uwsgi.ini", "--http-auto-chunked", "--http-keepalive"]
