version: '3'

services:
  webserver:
    image: nginx:alpine
    container_name: webserver_01
    ports:
      - "80:80"
    volumes:
      - ./webserver/nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    restart: always

  backend:
    container_name: backend_01
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        CODE: $BUILD_DIR/kbs_backend
    env_file: backend/env.list
    environment:
      SERVER_IP: $IP_ADDRESS
      SERVER_PORT: "8000"
    expose:
      - "8000" #must be identical to SERVER_PORT
    restart: always